export const CARGAR_LISTA='CARGAR_LISTA';
export const CARGAR_LISTA_OK='CARGAR_LISTA_OK';
export const CARGAR_LISTA_ERROR='CARGAR_LISTA_ERROR';
export const CARGAR_LISTA_INFORMACION='CARGAR_LISTA_INFORMACION';
