export const CARGAR_LISTA='CARGAR_LISTA';
export const CARGAR_LISTA_OK='CARGAR_LISTA_OK';
export const CARGAR_LISTA_ERROR='CARGAR_LISTA_ERROR';
export const CARGAR_LISTA_INFORMACION='CARGAR_LISTA_INFORMACION';

    //Rappitendero/PublicacionesR

export const CARGAR_LISTA_RAPPI='CARGAR_LISTA_RAPPI';
export const CARGAR_LISTA_OK_RAPPI='CARGAR_LISTA_OK_RAPPI';
export const CARGAR_LISTA_ERROR_RAPPI='CARGAR_LISTA_ERROR_RAPPI';
export const CARGAR_LISTA_INFORMACION_RAPPI='CARGAR_LISTA_INFORMACION_RAPPI';